# Every time this file is updated, *remember* to
#
# - update the sha256 for `fenix.fromToolchainFile` call in flake.nix

[toolchain]
channel = "1.90.0"
components = [
    "clippy",
    "rust-src",
    "rustfmt",
    "rust-analyzer",
    "llvm-tools"
]
targets = [
    "armv7r-none-eabi",
    "armv7r-none-eabihf",
    "armv7a-none-eabi",
]
