[[language]]
name = "rust"

[language-server.rust-analyzer.config]
rust-analyzer.checkOnSave.allTargets = false
rust-analyzer.checkOnSave.extraArgs = ["--bins"]

# rust-analyzer.linkedProjects = [ "./embedded/Cargo.toml", "./Cargo.toml", "./hil-tests/Cargo.toml" ]

